### ISSUE TITLE
WIP: Format data anggota.

### ISSUE THREAD

**Issue by indrakaw** [ponorogodev/daftar-developer#1]
Apakah harus individual atau daftar?

**Comment by dikiaap** [comment]
Kedua-duanya mas.

**Comment by indrakaw** [comment]
K.

**Comment by indrakaw** [comment]
Saya punya ide yaitu adanya generated file. Jadi, ada 2:
- subfolder `data/`, dan
- berkas `members.md` 

Detail:
- `data/` yang berisikan data anggota individu, 
  - misal: `data/dikiaap.md` yang berisikan data member @dikiaap .
  - format filename: `{username}.md`
  - untuk isi setiap idividual: WIP
- `members.md` adalah hasil compiled dari seluruh pemasukan pada folder `data`
  - ini dibuat dengan automation oleh script, semisal `Makefile` atau `Rakefile`
  - kalau bisa, terintegrasi dengan CI, jadi hanya perlu commit ke subfolder `data/`
  - untuk struktur `members.md` dan bagaimana scriptnya: WIP

Dengan demikian, diharapkan data ini bisa digunakan ulang untuk keperluan lain.

**Comment by dikiaap** [comment]
Terimakasih usulannya, bagus.

**Comment by hujianto** [comment]
Pripun niki carane daftar Mas fork dulu, lajeng pull request ?

**Comment by dikiaap** [comment]
@hujianto Iya mas, bener. Contoh style listnya ikutin sama yang di atasnya saja.

**Comment by hujianto** [comment]
Oh siap... Nuwun

**Comment by dikiaap** [comment]
Closed. Kita gunakan yang sementara untuk saat ini.

**Comment by indrakaw** [comment]
Ditunggu developer-developer tunas bangsa kita!

**Comment by dikiaap** [comment]
@indrakaw @indrakaw Ya mas. All the best. Selamat maju dan berkarya.
